### ISSUE TITLE
settings items aren't displayed.

### ISSUE THREAD

**Issue by amrg101** [MFlisar/MaterialPreferences#1]
I investigated it and found the source of the problem, fixed it myself until I found this good-looking comment, uncomment it and bug was fixed.
https://github.com/MFlisar/MaterialPreferences/blob/2e5ad6da7af581386560b963605186659d669c9f/library-preference-screen/src/main/java/com/michaelflisar/materialpreferences/preferencescreen/recyclerview/PreferenceAdapter.kt#L47
the only way to update rv adapter was to add a visibilityDependsOn  with Dependency object which was triggering `updateCurrentFilteredItems(true)` that updated the adapter list, also I found out that the object is leaking when in fragment, so I hope you investigate and fix it.

Keep up the good work!

**Comment by MFlisar** [comment]
**Bug - Items not visible**

I fixed that here - of course, its better to get the initial state of visibilities, set the list and then observe only changes and that's what's happening now:

https://github.com/MFlisar/MaterialPreferences/blob/6436398048de8eb9ed19bb7c0fea40dd01cc6291/library-preference-screen/src/main/java/com/michaelflisar/materialpreferences/preferencescreen/recyclerview/PreferenceAdapter.kt#L53-L83

**Leak**

I use the library in my newest app which I'm testing quite heavily and which uses `LeakCanary` in it without seeing any leaks yet - where do you see a leak? Any hints?

**Comment by MFlisar** [comment]
found something that may have lead to using the wrong scope inside the adapter - just open a new issue if you still find a leak in v1.0.4
