### ISSUE TITLE
disabled switch showing only holder

### ISSUE THREAD

**Issue by amrg101** [MFlisar/MaterialPreferences#5]
when the switch is disabled by default or dependency it seems that the switch is not drawn.
see this image: https://ibb.co/KjtWzV7

**Comment by MFlisar** [comment]
I disabled "color tinting" completely in my the root layout - disabled states are visually represented by a forced "on top" alpha only now which makes more sense anyways and additionally, it will never influence the color of a view - the view itself will control its color based on its state like enabled/disabled and so on...

**Comment by amrg101** [comment]
I wanted to control the color int the first place, so it worked for me.
but i think that your solution is making more sense as it is more stable for most users. 
good work!
