### ISSUE TITLE
Add encryption to Shared Preferences

### ISSUE THREAD

**Issue by Wrakor** [MFlisar/MaterialPreferences#8]
SharedPreferences data is not safe from apk extraction/reverse engineering. Would be great if this had encrypted data.

**Comment by MFlisar** [comment]
Check out the encryption branch: https://github.com/MFlisar/MaterialPreferences/tree/encryption

Here's the interface that needs to be implemented:
https://github.com/MFlisar/MaterialPreferences/blob/encryption/library/src/main/java/com/michaelflisar/materialpreferences/core/interfaces/StorageEncryption.kt

And here's a very simple example of an implementation for the encryption:
https://github.com/MFlisar/MaterialPreferences/blob/encryption/demo/src/main/java/com/michaelflisar/materialpreferences/demo/DemoStorageEncryption.kt

**Suggestion**

I implemented the basic logic for such a feature - if you fork my repo and create a new module "library-encryption-aes" or whatever algorithm is your favorite and create an implementation of the `StorageEncryption` interface from above I would be happy to merge it... Alternatively, if you write the implementation and simply share it with me I'd add it to my library as well...

**Comment by MFlisar** [comment]
I've done it myself already now as I just felt like doing it and had time for it...

Check out following please:
https://github.com/MFlisar/MaterialPreferences/releases/tag/1.1.0

**Comment by Wrakor** [comment]
Thank you ;)
